# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a3889056ab7b13db1097507f72eb66ff4baad6281fbcc5e2ce7adb51d81e177705e79cc1345630e9b84e3b76e8a35b6b116e64d81daccbf60ac59c01f083e97a

test:
  secret_key_base: 3ea81a0c63e3b4bb55f248e28ce83baca3d1236de5ddd1e70da8f02fee255d3766b05ec49522e89db3b66ef102b8fb7a4ba92ac371fba0fff76db55ccd333c1d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
